const modules=[['dashboard','🏠 Dashboard','Centro de mando'],['calendar','📅 Calendario','Día / semana / mes'],['tasks','✅ Tareas','Kanban y pendientes'],['cases','⚖️ Causas','RIT, tribunal y plazos'],['clients','👥 Clientes','CRM jurídico'],['finance','💰 Honorarios','Cobranza y flujo'],['audits','🏢 Auditorías','Comunidades e informes'],['docs','📂 Documentos','Biblioteca y modelos'],['ai','🤖 IA Jurídica','Generador de escritos'],['notes','📝 Notas','Ideas y minutas'],['settings','⚙️ Ajustes','Sistema']];
const storeKey='fabiana_os_ultra_v1';let DB=JSON.parse(localStorage.getItem(storeKey)||'{}');
const defaults={events:[],tasks:[],cases:[],clients:[],payments:[],audits:[],docs:[],notes:[]}; DB={...defaults,...DB};
function save(){localStorage.setItem(storeKey,JSON.stringify(DB));render(current)}let current='dashboard';
nav.innerHTML=modules.map(m=>`<button class="navbtn" onclick="render('${m[0]}')">${m[1]}</button>`).join('');
function setTitle(id){let m=modules.find(x=>x[0]==id);pageTitle.textContent=m[1].replace(/^[^ ]+ /,'');pageSub.textContent=m[2];document.querySelectorAll('.navbtn').forEach((b,i)=>b.classList.toggle('active',modules[i][0]==id))}
function render(id='dashboard'){current=id;setTitle(id);({dashboard,calendar,tasks,cases,clients,finance,audits,docs,ai,notes,settings}[id])()}
function fmt(n){return new Intl.NumberFormat('es-CL').format(n||0)}function today(){return new Date().toISOString().slice(0,10)}
function upcoming(){return DB.events.filter(e=>e.date>=today()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,6)}
function dashboard(){let due=DB.tasks.filter(t=>t.status!='Hecho').length, aud=DB.events.filter(e=>e.type=='Audiencia'&&e.date>=today()).length, pend=DB.payments.filter(p=>p.status!='Pagado').reduce((s,p)=>s+(+p.amount||0),0);content.innerHTML=`<div class="grid"><div class="card metric"><span>Compromisos próximos</span><b>${upcoming().length}</b></div><div class="card metric"><span>Tareas pendientes</span><b>${due}</b></div><div class="card metric"><span>Audiencias futuras</span><b>${aud}</b></div><div class="card metric"><span>Honorarios pendientes</span><b>$${fmt(pend)}</b></div></div><div class="row"><div class="card"><h2>Agenda próxima</h2><div class="list">${upcoming().map(eventItem).join('')||'<p>Sin compromisos.</p>'}</div></div><div class="card"><h2>Prioridad crítica</h2><div class="list">${DB.tasks.filter(t=>t.priority=='Alta'&&t.status!='Hecho').slice(0,6).map(taskItem).join('')||'<p>Sin tareas críticas.</p>'}</div></div></div><div class="row"><div class="card"><h2>Causas activas</h2>${table(['RIT','Cliente','Tribunal','Próxima gestión'],DB.cases.slice(0,5).map(c=>[c.rit,c.client,c.court,c.next]))}</div><div class="card"><h2>Auditorías</h2>${table(['Comunidad','Estado','Riesgo'],DB.audits.slice(0,5).map(a=>[a.name,a.status,a.risk]))}</div></div>`}
function eventItem(e){return `<div class="item"><div><b>${e.title}</b><div class="small">${e.date} ${e.time||''} · ${e.type||'Evento'} · ${e.place||''}</div></div><span class="pill">${e.priority||'Normal'}</span></div>`}
function taskItem(t){return `<div class="item"><div><b>${t.title}</b><div class="small">${t.due||'sin fecha'} · ${t.area||''}</div></div><span class="pill ${t.priority=='Alta'?'red':''}">${t.status||'Pendiente'}</span></div>`}
function table(h,rows){return `<table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c||''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function addBtn(type,label){return `<button onclick="openModal('${type}')">＋ ${label}</button>`}
function calendar(){let d=new Date(), y=d.getFullYear(), m=d.getMonth();let first=new Date(y,m,1), last=new Date(y,m+1,0);let blanks=(first.getDay()+6)%7;let days=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];let html=days.map(x=>`<b>${x}</b>`).join('');for(let i=0;i<blanks;i++)html+='<div></div>';for(let n=1;n<=last.getDate();n++){let date=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;let ev=DB.events.filter(e=>e.date==date);html+=`<div class="day"><b>${n}</b>${ev.map(e=>`<div class="event">${e.time||''} ${e.title}</div>`).join('')}</div>`}content.innerHTML=`<div class="tabs">${addBtn('event','Compromiso')}<button class="secondary" onclick="alert('Vista semana/día se activa en la siguiente versión con agenda horaria completa.')">Vista Día/Semana</button></div><div class="calendar">${html}</div>`}
function tasks(){let lanes=['Pendiente','En curso','En revisión','Hecho'];content.innerHTML=`<div class="tabs">${addBtn('task','Tarea')}</div><div class="kanban">${lanes.map(l=>`<div class="lane"><h3>${l}</h3>${DB.tasks.filter(t=>(t.status||'Pendiente')==l).map(taskItem).join('')}</div>`).join('')}</div>`}
function cases(){content.innerHTML=`<div class="tabs">${addBtn('case','Causa')}</div><div class="card">${table(['RIT/RUC','Materia','Cliente','Tribunal','Estado','Próxima gestión'],DB.cases.map(c=>[c.rit,c.matter,c.client,c.court,c.status,c.next]))}</div>`}
function clients(){content.innerHTML=`<div class="tabs">${addBtn('client','Cliente')}</div><div class="grid">${DB.clients.map(c=>`<div class="card"><h3>${c.name}</h3><p>${c.rut||''}</p><p>📞 ${c.phone||''}<br>✉️ ${c.email||''}</p><span class="pill">${c.area||'General'}</span></div>`).join('')}</div>`}
function finance(){let paid=DB.payments.filter(p=>p.status=='Pagado').reduce((s,p)=>s+(+p.amount||0),0), pending=DB.payments.filter(p=>p.status!='Pagado').reduce((s,p)=>s+(+p.amount||0),0);content.innerHTML=`<div class="grid"><div class="card metric"><span>Cobrado</span><b>$${fmt(paid)}</b></div><div class="card metric"><span>Pendiente</span><b>$${fmt(pending)}</b></div></div><br><div class="tabs">${addBtn('payment','Honorario')}</div><div class="card">${table(['Cliente','Concepto','Monto','Vence','Estado'],DB.payments.map(p=>[p.client,p.concept,'$'+fmt(p.amount),p.due,p.status]))}</div>`}
function audits(){content.innerHTML=`<div class="tabs">${addBtn('audit','Auditoría')}<button class="gold" onclick="genAuditReport()">Generar Informe Asamblea</button></div><div class="card">${table(['Comunidad','Periodo','Estado','Riesgo','Hallazgo principal'],DB.audits.map(a=>[a.name,a.period,a.status,a.risk,a.finding]))}</div>`}
function docs(){content.innerHTML=`<div class="tabs">${addBtn('doc','Documento')}</div><div class="card">${table(['Nombre','Tipo','Cliente/Causa','Ubicación'],DB.docs.map(d=>[d.name,d.type,d.ref,d.url]))}</div>`}
function notes(){content.innerHTML=`<div class="tabs">${addBtn('note','Nota')}</div><div class="grid">${DB.notes.map(n=>`<div class="card"><h3>${n.title}</h3><p>${n.text}</p><span class="small">${n.date||today()}</span></div>`).join('')}</div>`}
function ai(){content.innerHTML=`<div class="card"><h2>Generador IA Jurídica local</h2><p>Completa los datos y genera una estructura editable para demanda, apelación, objeción, correo o informe.</p><div class="form"><select id="aiType"><option>Demanda de familia</option><option>Objeción liquidación alimentos</option><option>Apelación</option><option>Correo jurídico</option><option>Informe auditoría comunidad</option></select><input id="aiMatter" placeholder="Materia / asunto"><textarea class="full" id="aiFacts" placeholder="Hechos relevantes"></textarea><textarea class="full" id="aiAsk" placeholder="Petición concreta"></textarea><button onclick="generateDraft()">Generar borrador</button></div><pre id="draft" class="card" style="white-space:pre-wrap;margin-top:16px"></pre></div>`}
function settings(){content.innerHTML=`<div class="card"><h2>Ajustes y roadmap</h2><p>Versión Ultra PWA local. Pendiente para versión servidor: SQLite/PostgreSQL, sincronización real Google Calendar/Gmail, .exe con Electron, usuarios y nube.</p><button onclick="localStorage.removeItem(storeKey);location.reload()" class="secondary">Borrar base local</button></div>`}
function formFields(type){const common={event:['title:Título','date:Fecha:date','time:Hora:time','type:Tipo:select:Audiencia,Reunión,Vencimiento,Tarea,Personal','place:Lugar','priority:Prioridad:select:Normal,Alta,Baja'],task:['title:Tarea','due:Vence:date','area:Área','priority:Prioridad:select:Normal,Alta,Baja','status:Estado:select:Pendiente,En curso,En revisión,Hecho'],case:['rit:RIT/RUC','matter:Materia','client:Cliente','court:Tribunal','status:Estado','next:Próxima gestión:date'],client:['name:Nombre','rut:RUT','phone:Teléfono','email:Correo','area:Área'],payment:['client:Cliente','concept:Concepto','amount:Monto:number','due:Vence:date','status:Estado:select:Pendiente,Pagado,Vencido'],audit:['name:Comunidad','period:Periodo','status:Estado','risk:Riesgo:select:Bajo,Medio,Alto','finding:Hallazgo principal'],doc:['name:Nombre','type:Tipo','ref:Cliente/Causa','url:Ubicación o link'],note:['title:Título','date:Fecha:date','text:Texto:textarea']}; return common[type]}
function openModal(type){if(type=='quick'){modalBody.innerHTML=`<h2>Nuevo registro</h2><div class="grid">${['event','task','case','client','payment','audit','doc','note'].map(t=>`<button onclick="openModal('${t}')">${t}</button>`).join('')}</div>`;modal.classList.add('show');return}let fields=formFields(type);modalBody.innerHTML=`<h2>Nuevo ${type}</h2><div class="form">${fields.map(f=>fieldHtml(f)).join('')}<button onclick="submitForm('${type}')">Guardar</button></div>`;modal.classList.add('show')}
function fieldHtml(f){let [k,l,kind,opt]=f.split(':'); if(kind=='textarea')return `<textarea class="full" id="f_${k}" placeholder="${l}"></textarea>`; if(kind=='select')return `<select id="f_${k}">${opt.split(',').map(o=>`<option>${o}</option>`).join('')}</select>`; return `<input id="f_${k}" type="${kind||'text'}" placeholder="${l}">`}
function submitForm(type){let obj={};formFields(type).forEach(f=>{let k=f.split(':')[0];obj[k]=document.getElementById('f_'+k).value});let map={event:'events',task:'tasks',case:'cases',client:'clients',payment:'payments',audit:'audits',doc:'docs',note:'notes'};DB[map[type]].push(obj);closeModal();save()}
function closeModal(){modal.classList.remove('show')}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('fabiana_theme',document.body.classList.contains('dark')?'dark':'light')}if(localStorage.getItem('fabiana_theme')=='dark')document.body.classList.add('dark');
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}));a.download='respaldo_fabiana_os.json';a.click()}
function importData(e){let f=e.target.files[0];let r=new FileReader();r.onload=()=>{DB=JSON.parse(r.result);save()};r.readAsText(f)}
function notifyMe(){Notification.requestPermission().then(p=>{if(p=='granted')new Notification('Fabiana OS activo',{body:'Los avisos del navegador quedaron habilitados.'})})}
function generateDraft(){draft.textContent=`${aiType.value.toUpperCase()}\n\nI. MATERIA\n${aiMatter.value}\n\nII. ANTECEDENTES DE HECHO\n${aiFacts.value}\n\nIII. FUNDAMENTOS\nSe solicita estructurar la presentación conforme a los antecedentes, el mérito de los documentos y la normativa aplicable.\n\nIV. PETICIÓN\n${aiAsk.value}\n\nV. DOCUMENTOS / PRUEBA\nAgregar individualización de documentos, correos, comprobantes, resoluciones y demás antecedentes.\n\n[Texto base editable generado por Fabiana OS]`}
function genAuditReport(){alert('Informe base generado: Hallazgos, Riesgos, Recomendaciones y Conclusión. En la siguiente versión se exporta a Word/PDF automáticamente.')}
function seedDemo(){DB.events.push({title:'Audiencia alimentos',date:today(),time:'09:00',type:'Audiencia',place:'Juzgado de Familia',priority:'Alta'});DB.tasks.push({title:'Preparar objeción de liquidación',due:today(),area:'Familia',priority:'Alta',status:'Pendiente'});DB.cases.push({rit:'C-1234-2026',matter:'Alimentos',client:'Cliente Demo',court:'Juzgado de Familia',status:'Activa',next:today()});DB.clients.push({name:'Cliente Demo',rut:'11.111.111-1',phone:'+56 9 0000 0000',email:'cliente@demo.cl',area:'Familia'});DB.payments.push({client:'Cliente Demo',concept:'Honorarios causa alimentos',amount:450000,due:today(),status:'Pendiente'});DB.audits.push({name:'Comunidad Santa María',period:'2° semestre 2025',status:'En revisión',risk:'Medio',finding:'Egresos sin respaldo completo'});save()}
render('dashboard');
